# Generated by Django 5.1.1 on 2024-11-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.IntegerField(null=5),
            preserve_default=5,
        ),
    ]
