# Generated by Django 5.1.1 on 2024-11-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_remove_client_image_client_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='products',
        ),
    ]
