# Generated by Django 5.1.1 on 2024-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_products_description_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='pdescription',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='products',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='pprice',
        ),
        migrations.AddField(
            model_name='products',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
